# Generated by Django 6.0.5 on 2026-05-27 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Petrol/Diesel', 'Petrol/Diesel'), ('LPG', 'LPG'), ('EV', 'EV')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('octane', models.CharField(blank=True, max_length=20, null=True)),
                ('connector', models.CharField(blank=True, max_length=20, null=True)),
                ('power_output', models.CharField(blank=True, max_length=20, null=True)),
                ('has_backup_generator', models.BooleanField(default=False)),
                ('lpg_type', models.JSONField(blank=True, default=list, null=True)),
                ('lpg_price_per_kg', models.FloatField(blank=True, null=True)),
                ('delivery_available', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
