# Generated by Django 6.0.5 on 2026-06-11 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Petrol/Diesel", "Petrol/Diesel"),
                            ("LPG", "LPG"),
                            ("EV", "EV"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Closed", "Closed")],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20, null=True)),
                ("price", models.CharField(blank=True, max_length=50, null=True)),
                ("octane", models.CharField(blank=True, max_length=20, null=True)),
                ("connector", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "power_output",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("has_backup_generator", models.BooleanField(default=False)),
                ("lpg_type", models.JSONField(blank=True, default=list, null=True)),
                ("lpg_price_per_kg", models.FloatField(blank=True, null=True)),
                ("delivery_available", models.BooleanField(default=False)),
                ("petrol_data", models.JSONField(blank=True, default=dict, null=True)),
                ("diesel_data", models.JSONField(blank=True, default=dict, null=True)),
                ("ev_data", models.JSONField(blank=True, default=list, null=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
