# Generated by Django 6.0.5 on 2026-05-29 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
