# Generated by Django 6.0.5 on 2026-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='diesel_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='ev_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='petrol_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
