# Generated by Django 6.0.5 on 2026-06-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("unusual_price", "Unusual Price"),
                            ("poor_quality", "Poor Fuel Quality"),
                            ("fuel_shortage", "Fuel Shortage"),
                            ("charger_not_working", "Charger Not Working"),
                            ("wrong_connector", "Wrong Connector Type"),
                            ("slow_charging", "Slow Charging Speed"),
                            ("price_higher", "Price Higher Than Listed"),
                            ("damaged_charger", "Charger Damaged/Vandalized"),
                            ("stopped_unexpectedly", "Charging Stopped Unexpectedly"),
                            ("no_backup", "No Backup Generator"),
                            ("leakage", "Suspected Gas Leakage"),
                            ("underfilling", "Underfilling of Cylinders"),
                            ("long_queue", "Long Queue"),
                            ("slow_service", "Slow Refill Service"),
                            ("cylinder_not_available", "Cylinder Size Not Available"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="stations.station",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(help_text="Rating from 1 to 5 stars")),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="stations.station",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
