# Generated by Django 6.0.5 on 2026-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="admin_notes",
        ),
        migrations.RemoveField(
            model_name="report",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="report",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="report",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("unusual_price", "Unusual Price"),
                    ("poor_quality", "Poor Fuel Quality"),
                    ("fuel_shortage", "Fuel Shortage"),
                    ("charger_not_working", "Charger Not Working"),
                    ("wrong_connector", "Wrong Connector Type"),
                    ("slow_charging", "Slow Charging Speed"),
                    ("price_higher", "Price Higher Than Listed"),
                    ("damaged_charger", "Charger Damaged/Vandalized"),
                    ("stopped_unexpectedly", "Charging Stopped Unexpectedly"),
                    ("no_backup", "No Backup Generator"),
                    ("leakage", "Suspected Gas Leakage"),
                    ("underfilling", "Underfilling of Cylinders"),
                    ("long_queue", "Long Queue"),
                    ("slow_service", "Slow Refill Service"),
                    ("cylinder_not_available", "Cylinder Size Not Available"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
